# Generated by Django 4.2.13 on 2024-06-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='corporations.corporation')),
            ],
        ),
    ]
